"""
A.N.T. Layer 3 - Test Planner Engine v2
Orchestrates: IssuerFetcher -> LLMRouter -> DocBuilder
SOP Reference: architecture/test_planner_sop.md
"""

import json
import os
import sys
from datetime import datetime
from docx import Document

# Ensure tools/ is on the path so we can import siblings
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from issue_fetcher import fetch_issue
from llm_router import route_to_llm, route_gap_analysis, TOOL_COLUMN_LABEL


class TestPlannerEngine:
    """
    Orchestrates the 3-step B.L.A.S.T. pipeline:
      Step 1 - Issue Ingestion   (issue_fetcher.py)
      Step 2 - LLM Extraction    (llm_router.py)
      Step 3 - Document Assembly (python-docx)
    """

    def __init__(self, payload_path: str):
        self.payload_path  = payload_path
        self.config        = self._load_payload()
        self.template_path = os.path.join(
            os.path.dirname(__file__), "..", "Templates", "Test Plan - Template.docx"
        )

    # ── Payload ───────────────────────────────────────────────────────────────

    def _load_payload(self) -> dict:
        try:
            with open(self.payload_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            raise RuntimeError(f"Engine Failure: Could not load payload from {self.payload_path}. {e}")

    # ── Step 1 ────────────────────────────────────────────────────────────────

    def fetch_issue_context(self) -> str:
        manual = self.config.get("manualRequirements", "").strip()
        if manual:
            print(f"[Engine] Using manual requirements context ({len(manual)} chars).")
            return manual
        
        context = fetch_issue(self.config)
        print(f"[Engine] Issue context fetched - {len(context)} chars.")
        return context

    # ── Step 2 ────────────────────────────────────────────────────────────────

    def generate_test_cases(self, context_text: str) -> dict:
        """Routes context to the selected LLM via llm_router.py."""
        custom = self.config.get("customInstructions", "")
        return route_to_llm(self.config, context_text, custom_instructions=custom)

    def analyze_requirement_gaps(self, context_text: str) -> dict:
        """Routes context to gap analysis via llm_router.py."""
        return route_gap_analysis(self.config, context_text)

    # ── Step 3 ────────────────────────────────────────────────────────────────

    def generate_docx_plan(self, data_schema: dict) -> str:
        """
        Populates the Test Plan template (.docx) with the generated test cases.
        Uses dynamic tool column label per gemini.md Tool ID Mapping.
        """
        print("[Engine] Assembling Word document from test case schema...")
        tool        = data_schema.get("selectedTool", self.config.get("selectedTool", "Jira"))
        tool_label  = TOOL_COLUMN_LABEL.get(tool, f"{tool} ID")
        plan_title  = data_schema.get("testPlanTitle", f"Test Plan - {self.config.get('issueId', 'Unknown')}")
        test_cases  = data_schema.get("testCases", [])

        # Load template or create blank doc as fallback
        try:
            doc = Document(self.template_path)
            print(f"[Engine] Loaded template: {self.template_path}")
        except Exception as e:
            print(f"[Engine] Template not found ({e}), creating blank document.")
            doc = Document()
            doc.add_heading("AntiGravity - AI Generated Test Plan", 0)

        # ── Inject generated content ──────────────────────────────────────────
        doc.add_heading(plan_title, level=1)
        doc.add_paragraph(
            f"Generated by AntiGravity Test Planner using {self.config.get('llmProvider', 'LLM')} "
            f"with Zero-Hallucination Extraction Protocol.\n"
            f"Source: {tool} - Ticket: {self.config.get('issueId', 'N/A')}"
        )

        # ── Inject Requirements Profile ──────────────────────────────────────
        rp = data_schema.get("requirementsProfile", {})
        doc.add_heading("Requirements Extraction Profile", level=2)
        
        doc.add_heading("Feature Scope", level=3)
        doc.add_paragraph(rp.get("featureScope", "Not defined."))
        
        for section, key in [
            ("Acceptance Criteria (AC)", "acceptanceCriteria"),
            ("Business Rules",           "businessRules"),
            ("Field Validations",        "fieldValidations"),
            ("Technical Dependencies",   "technicalDependencies"),
            ("Error Handling",           "errorHandling")
        ]:
            items = rp.get(key, [])
            if items:
                doc.add_heading(section, level=3)
                for item in items:
                    # Robust bulleting: Try the style, fallback to manual bullet
                    try:
                        doc.add_paragraph(item, style='List Bullet')
                    except Exception:
                        doc.add_paragraph(f"• {item}")

        # ── Inject Test Cases ────────────────────────────────────────────────
        if not test_cases:
            doc.add_paragraph("WARNING: No test cases were generated. Verify the ticket contains sufficient ACs.")
        else:
            doc.add_heading("Test Cases Execution Table", level=2)
            doc.add_paragraph(f"Total Test Cases: {len(test_cases)} | Tool: {tool}")

            # ── Dynamic table ──────────────────────────────────────────────────
            table = doc.add_table(rows=1, cols=10)
            try:
                table.style = "Table Grid"
            except Exception:
                pass

            headers = [
                "Test Case ID", tool_label, "Module / Feature",
                "Test Case Title", "Preconditions", "Test Steps",
                "Test Data", "Expected Result", "Priority", "Test Type",
            ]
            for i, h in enumerate(headers):
                table.rows[0].cells[i].text = h

            for tc in test_cases:
                row = table.add_row().cells
                row[0].text = str(tc.get("testCaseId",     ""))
                row[1].text = str(tc.get("toolTicketId",   tc.get("toolId", "")))
                row[2].text = str(tc.get("module",         ""))
                row[3].text = str(tc.get("testCaseTitle",  ""))
                row[4].text = str(tc.get("preconditions",  ""))
                row[5].text = str(tc.get("testSteps",      ""))
                row[6].text = str(tc.get("testData",       ""))
                row[7].text = str(tc.get("expectedResult", ""))
                row[8].text = str(tc.get("priority",       ""))
                row[9].text = str(tc.get("testType",       ""))

        # ── Save to .tmp/ ──────────────────────────────────────────────────────
        # On Vercel (Linux), use /tmp for writability. On local Windows, use root .tmp
        if os.name == 'nt':
            tmp_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".tmp"))
        else:
            tmp_dir = "/tmp"
        
        os.makedirs(tmp_dir, exist_ok=True)
        ts     = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_id = str(self.config.get('issueId', 'output')).replace('/', '_').replace('\\', '_')
        output = os.path.join(tmp_dir, f"TestPlan_{output_id}_{ts}.docx")
        doc.save(output)
        print(f"[Engine] Document saved -> {output}")
        return output

    # ── Pipeline entry points ─────────────────────────────────────────────────

    def run_pipeline(self) -> str:
        """Full pipeline: fetch -> generate test cases -> assemble .docx"""
        print("=== B.L.A.S.T Core Engine - Test Plan Pipeline ===")
        context     = self.fetch_issue_context()
        test_cases  = self.generate_test_cases(context)
        output_path = self.generate_docx_plan(test_cases)
        print("=== Pipeline Complete ===")
        return os.path.abspath(output_path)

    def run_test_cases_pipeline(self) -> tuple:
        """Original pipeline returning JSON for the frontend."""
        print("=== B.L.A.S.T Core Engine - Test Cases Pipeline ===")
        context     = self.fetch_issue_context()
        test_cases  = self.generate_test_cases(context)
        # We don't generate DOCX for pure test case requests anymore if the user wants dedicated XLSX
        # But we still return context + cases
        return None, test_cases

    def run_gap_analysis(self) -> dict:
        """Fetch issue context -> run LLM gap analysis -> return JSON dict."""
        print("=== B.L.A.S.T Core Engine - Gap Analysis Pipeline ===")
        context  = self.fetch_issue_context()
        analysis = self.analyze_requirement_gaps(context)
        print("=== Gap Analysis Complete ===")
        return analysis
